### ISSUE TITLE
Error while flashing: SWIM error 0x04

### ISSUE THREAD

**Issue by elishowk** [emmebrusa/TSDZ2-Smart-EBike-860C#3]
Hi,

Thanks for the work on this firmware. I'm new to this whole subject and I unable to flash the latest firmware following [the instructions here](https://github.com/OpenSourceEBike/TSDZ2_wiki/wiki/Flash-the-firmware-on-TSDZ2).

Here's me logs:

```
sudo stm8flash -c stlinkv2 -p 'stm8s105?6' -w TSDZ2-v20.1C.3-860C-NEW.hex
Determine FLASH area
STLink: v2, JTAG: v17, SWIM: v4, VID: 8304, PID: 4837
Due to its file extension (or lack thereof), "TSDZ2-v20.1C.3-860C-NEW.hex" is considered as INTEL HEX format!
24029 bytes at 0x8000... SWIM error 0x04
```

I also tried without success to convert the original HEX file to Raw binary.
I have [stm8flash cloned from the latest commit on master](https://github.com/vdudouyt/stm8flash/commit/d304b0e823777f39eafb7ad69221c6f062f5959b).
The battery is fully charged and connected, and the 860C is already flashed with the same v20.1C3 version (and is ON while flashing).

I can't find information on the internet about the "swim error 0x04".
Could you help me please ?

**Comment by casperskodt1991** [comment]
Hi, I flashed this with success. I did it without power connected to the motor. The STlink is able to power the CPU for programming.
